---
title: "K-means"
author: "Amat Zahra"
date: "March 24, 2019"
output: html_document
---

data = read.csv("jobs.csv", header=TRUE)
names(data)
new_data = data[,c(7,8,9,10,11,14,16)]
numbers_only <- data[,-c(7,8,9,10,11,14,16)]

#turn the dataframe to be numeric

index <- sapply(numbers_only, is.factor)
numbers_only[index] <- lapply(numbers_only[index], function(x) as.numeric(as.character(x)))
new_data = cbind(new_data, numbers_only)

#now we have a proper dataset with numbers and factors

write.csv(new_data, "new_data.csv")
data = read.csv("new_data.csv")

#omitting nas
n_data <- na.omit(data)
n_data 


#k-means
results = kmeans(n_data[,c(2,3,4,5,6,7,8,9,10,11,12,13,14,17,18)], 15)
results


#plot - occupation, marital status, education and work
plot(n_data[,c(2,3,5,7)], col = results$cluster)

#plot - treat, income, job_seek
plot(n_data[,c(4,5,6,7,8)], col = results$cluster)

#plot - age, depress1, depress2
plot(n_data[,c(6,4,9,10)], col = results$cluster)


#plot - 
plot(n_data[,c(5,7,10)], col = results$cluster)

#plot - 
plot(n_data[,c(2,3,4,5,6,7,10,11,12,13,14)], col = results$cluster)






